version: '2'

services:

  camilo:
    restart: always
    privileged: true
    image: chamilo
    ports:
      - 8001:80
    links:
      - camilo-mysql:mysql
    volumes:
      - /home/joelmsilva/chamilo2/:/var/www/html/

  camilo-mysql:
    restart: always
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=Standard1
    ports:
      - 8306:3306
    volumes:
      - /home/vagrant/chamilo-docker/mysql/:/var/lib/mysql/
