version: '3.7'

services:

  chamilo:
    restart: always
    privileged: true
    image: cambacoop/chamilo:latest
    ports:
      - 8001:80
    links:
      - chamilo-mysql:mysql
    volumes:
      - /home/chamilo/:/var/www/html/
    environment:
      - VIRTUAL_HOST=chamilo.napore.com


  chamilo-mysql:
    restart: always
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=Standard1
    ports:
      - 8306:3306
    volumes:
      - /home/chamilo-docker/mysql/:/var/lib/mysql/

networks:
  default:
    external:
      name: nginx-proxy
